map_type:             costmap
obstacle_range:       2.5
raytrace_range:       3.0
transform_tolerance:  0.2
footprint:            [[0.2, 0.25], [0.2, -0.25], [-0.2, -0.25], [-0.2,0.25]]
#robot_radius:        0.0 
inflation_radius:     0.3
observation_sources:  laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /person/laser/scan, marking: true, clearing: true}