global_costmap:
  global_frame:      map
  robot_base_frame:  human_base
  update_frequency:  10.0
  publish_frequency: 10.0
  width:             50.0
  height:            50.0
  resolution:        0.02
  static_map:        true
  rolling_window:    false