local_costmap:
  global_frame:      odom
  robot_base_frame:  human_base
  update_frequency:  10.0
  publish_frequency: 10.0
  width:             4.0
  height:            4.0
  resolution:        0.02
  static_map:        false
  rolling_window:    true